"""CIM-Builder: programmatic CIM model construction."""
# Layer 1 — primitives
from cimbuilder.object_builder import (
    new_base_voltage,
    new_bus_bar_section,
    new_connectivity_node,
    new_junction,
    new_breaker,
    new_disconnector,
    new_fuse,
    new_load_break_switch,
    new_power_transformer,
    new_power_transformer_end,
    new_ratio_tap_changer,
    new_tap_changer_control,
    new_ac_line_segment,
    new_per_length_sequence_impedance,
    new_linear_shunt_compensator,
    new_energy_consumer,
    new_synchronous_machine,
    new_power_electronics_connection,
    new_photo_voltaic_unit,
    new_battery_unit,
    new_wind_unit,
    new_analog,
    create_all_analog,
    new_discrete,
    new_one_terminal_object,
    new_two_terminal_object,
)

# Legacy substation builders (class-based API — replaced by topology_builder/ in Phase 3)
from cimbuilder.substation_builder import (
    SingleBusSubstation,
    DoubleBusSingleBreakerSubstation,
    BreakerAndHalfSubstation,
    MainAndTransferSubstation,
    RingBusSubstation,
    SectionalizedBusSubstation,
)

__all__ = [
    # primitives
    "new_base_voltage",
    "new_bus_bar_section",
    "new_connectivity_node",
    "new_junction",
    "new_breaker",
    "new_disconnector",
    "new_fuse",
    "new_load_break_switch",
    "new_power_transformer",
    "new_power_transformer_end",
    "new_ratio_tap_changer",
    "new_tap_changer_control",
    "new_ac_line_segment",
    "new_per_length_sequence_impedance",
    "new_linear_shunt_compensator",
    "new_energy_consumer",
    "new_synchronous_machine",
    "new_power_electronics_connection",
    "new_photo_voltaic_unit",
    "new_battery_unit",
    "new_wind_unit",
    "new_analog",
    "create_all_analog",
    "new_discrete",
    "new_one_terminal_object",
    "new_two_terminal_object",
    # legacy substation builders (Phase 3 will replace with functional API)
    "SingleBusSubstation",
    "DoubleBusSingleBreakerSubstation",
    "BreakerAndHalfSubstation",
    "MainAndTransferSubstation",
    "RingBusSubstation",
    "SectionalizedBusSubstation",
]
