"""CIM-Builder: programmatic CIM model construction."""
# Layer 4 — session classes
from cimbuilder.session import SubstationSession, FeederSession, NetworkSession

# Layer 1 — primitives
from cimbuilder.object_builder import (
    new_base_voltage,
    new_bus_bar_section,
    new_connectivity_node,
    new_junction,
    new_breaker,
    new_disconnector,
    new_fuse,
    new_load_break_switch,
    new_power_transformer,
    new_power_transformer_end,
    new_ratio_tap_changer,
    new_tap_changer_control,
    new_ac_line_segment,
    new_per_length_sequence_impedance,
    new_linear_shunt_compensator,
    new_energy_consumer,
    new_synchronous_machine,
    new_power_electronics_connection,
    new_photo_voltaic_unit,
    new_battery_unit,
    new_wind_unit,
    new_analog,
    create_all_analog,
    new_discrete,
    new_one_terminal_object,
    new_two_terminal_object,
)

# Layer 3 — topology functions
from cimbuilder.topology_builder import (
    new_single_bus_substation,
    add_feeder_to_single_bus,
    add_branch_to_single_bus,
    new_double_bus_single_breaker_substation,
    add_feeder_to_double_bus_single_breaker,
    add_branch_to_double_bus_single_breaker,
    new_main_and_transfer_substation,
    add_feeder_to_main_and_transfer,
    add_branch_to_main_and_transfer,
    new_ring_bus_substation,
    add_feeder_to_ring_bus,
    add_branch_to_ring_bus,
    new_sectionalized_bus_substation,
    add_feeder_to_sectionalized_bus,
    add_branch_to_sectionalized_bus,
    new_breaker_and_half_substation,
    add_feeder_to_breaker_and_half,
    add_branch_to_breaker_and_half,
)

# Legacy substation builders (class-based API — will become deprecation shims in Phase 5)
from cimbuilder.substation_builder import (
    SingleBusSubstation,
    DoubleBusSingleBreakerSubstation,
    BreakerAndHalfSubstation,
    MainAndTransferSubstation,
    RingBusSubstation,
    SectionalizedBusSubstation,
)

__all__ = [
    # session classes
    "SubstationSession",
    "FeederSession",
    "NetworkSession",
    # primitives
    "new_base_voltage",
    "new_bus_bar_section",
    "new_connectivity_node",
    "new_junction",
    "new_breaker",
    "new_disconnector",
    "new_fuse",
    "new_load_break_switch",
    "new_power_transformer",
    "new_power_transformer_end",
    "new_ratio_tap_changer",
    "new_tap_changer_control",
    "new_ac_line_segment",
    "new_per_length_sequence_impedance",
    "new_linear_shunt_compensator",
    "new_energy_consumer",
    "new_synchronous_machine",
    "new_power_electronics_connection",
    "new_photo_voltaic_unit",
    "new_battery_unit",
    "new_wind_unit",
    "new_analog",
    "create_all_analog",
    "new_discrete",
    "new_one_terminal_object",
    "new_two_terminal_object",
    # topology functions
    "new_single_bus_substation",
    "add_feeder_to_single_bus",
    "add_branch_to_single_bus",
    "new_double_bus_single_breaker_substation",
    "add_feeder_to_double_bus_single_breaker",
    "add_branch_to_double_bus_single_breaker",
    "new_main_and_transfer_substation",
    "add_feeder_to_main_and_transfer",
    "add_branch_to_main_and_transfer",
    "new_ring_bus_substation",
    "add_feeder_to_ring_bus",
    "add_branch_to_ring_bus",
    "new_sectionalized_bus_substation",
    "add_feeder_to_sectionalized_bus",
    "add_branch_to_sectionalized_bus",
    "new_breaker_and_half_substation",
    "add_feeder_to_breaker_and_half",
    "add_branch_to_breaker_and_half",
    # legacy substation builders (Phase 5 will add deprecation warnings)
    "SingleBusSubstation",
    "DoubleBusSingleBreakerSubstation",
    "BreakerAndHalfSubstation",
    "MainAndTransferSubstation",
    "RingBusSubstation",
    "SectionalizedBusSubstation",
]
